# Generated by Django 3.2.25 on 2025-08-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250806_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecreate',
            name='profile_image',
        ),
    ]
