# Generated by Django 3.2.25 on 2025-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_profilecreate_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCreate',
        ),
    ]
